---
AWSTemplateFormatVersion: "2010-09-09"
Description: This is a vpc for aws cloudformation
Resources:
  Daniyarvpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: True
      EnableDnsSupport: True
      Tags:
        - Key: "Name"
          Value: Banking
